/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGame,
  IGameInterface,
} from "../../../contracts/StartGame.sol/IGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
    ],
    name: "canExecuteMatch",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "executor",
        type: "address",
      },
    ],
    name: "playMatch",
    outputs: [
      {
        internalType: "uint8",
        name: "homeGoals",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "awayGoals",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGame__factory {
  static readonly abi = _abi;
  static createInterface(): IGameInterface {
    return new Interface(_abi) as IGameInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IGame {
    return new Contract(address, _abi, runner) as unknown as IGame;
  }
}
