/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  StartGame,
  StartGameInterface,
} from "../../../contracts/StartGame.sol/StartGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "gameAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "executor",
        type: "address",
      },
    ],
    name: "ExecutionRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "executor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "homeGoals",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "awayGoals",
        type: "uint8",
      },
    ],
    name: "MatchExecuted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
    ],
    name: "executeMatch",
    outputs: [
      {
        internalType: "uint8",
        name: "homeGoals",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "awayGoals",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "game",
    outputs: [
      {
        internalType: "contract IGame",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a03461007257601f61039338819003918201601f19168301916001600160401b038311848410176100775780849260209460405283398101031261007257516001600160a01b0381169081900361007257608052604051610305908161008e8239608051818181606501526102550152f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe6080604090808252600436101561001557600080fd5b600090813560e01c908163c3fe3e2814610241575063eb88936d1461003957600080fd5b346101a9576020918260031936011261023d578051632e863cb160e01b815260048035908201819052907f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316908581602481855afa9081156102335785916101f9575b50156101c057828491604482518094819333887f3b683a6bb09f2b66a0a123e652b360248df28e205f5783156912d52c444523d38480a36310c78d0d60e31b8352600483018890523360248401525af19485156101b357848096610162575b5050825160ff85811682528616602082015261015e9392339250907f55dee59e701076d06eaa92f1bcff61c1600d9bf0ca4f70e4f3e6e91aeb9c04c290604090a35160ff928316815292909116602083015281906040820190565b0390f35b918480929497508196503d83116101ac575b61017e8183610284565b810103126101a957509061019f61015e92610198856102bc565b94016102bc565b9390913880610103565b80fd5b503d610174565b50505051903d90823e3d90fd5b825162461bcd60e51b81526004810186905260126024820152714d61746368206973206e6f7420726561647960701b6044820152606490fd5b90508581813d831161022c575b6102108183610284565b810103126102285751801515810361022857386100a4565b8480fd5b503d610206565b84513d87823e3d90fd5b5080fd5b90503461023d578160031936011261023d577f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b90601f8019910116810190811067ffffffffffffffff8211176102a657604052565b634e487b7160e01b600052604160045260246000fd5b519060ff821682036102ca57565b600080fdfea26469706673582212204cd3e854fe1cf33dfd638f483c548caa0036f7d36251860a600ca29be57bfa0e64736f6c63430008150033";

type StartGameConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StartGameConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StartGame__factory extends ContractFactory {
  constructor(...args: StartGameConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    gameAddress: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(gameAddress, overrides || {});
  }
  override deploy(
    gameAddress: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(gameAddress, overrides || {}) as Promise<
      StartGame & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): StartGame__factory {
    return super.connect(runner) as StartGame__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StartGameInterface {
    return new Interface(_abi) as StartGameInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): StartGame {
    return new Contract(address, _abi, runner) as unknown as StartGame;
  }
}
