/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGameInterface extends Interface {
  getFunction(
    nameOrSignature: "canExecuteMatch" | "playMatch"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "canExecuteMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playMatch",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "canExecuteMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "playMatch", data: BytesLike): Result;
}

export interface IGame extends BaseContract {
  connect(runner?: ContractRunner | null): IGame;
  waitForDeployment(): Promise<this>;

  interface: IGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canExecuteMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [boolean],
    "view"
  >;

  playMatch: TypedContractMethod<
    [matchId: BigNumberish, executor: AddressLike],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canExecuteMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "playMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish, executor: AddressLike],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "nonpayable"
  >;

  filters: {};
}
