/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface StartGameInterface extends Interface {
  getFunction(nameOrSignature: "executeMatch" | "game"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ExecutionRequested" | "MatchExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "game", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "executeMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "game", data: BytesLike): Result;
}

export namespace ExecutionRequestedEvent {
  export type InputTuple = [matchId: BigNumberish, executor: AddressLike];
  export type OutputTuple = [matchId: bigint, executor: string];
  export interface OutputObject {
    matchId: bigint;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchExecutedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    executor: AddressLike,
    homeGoals: BigNumberish,
    awayGoals: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    executor: string,
    homeGoals: bigint,
    awayGoals: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    executor: string;
    homeGoals: bigint;
    awayGoals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StartGame extends BaseContract {
  connect(runner?: ContractRunner | null): StartGame;
  waitForDeployment(): Promise<this>;

  interface: StartGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "nonpayable"
  >;

  game: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "game"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ExecutionRequested"
  ): TypedContractEvent<
    ExecutionRequestedEvent.InputTuple,
    ExecutionRequestedEvent.OutputTuple,
    ExecutionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "MatchExecuted"
  ): TypedContractEvent<
    MatchExecutedEvent.InputTuple,
    MatchExecutedEvent.OutputTuple,
    MatchExecutedEvent.OutputObject
  >;

  filters: {
    "ExecutionRequested(uint256,address)": TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;
    ExecutionRequested: TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;

    "MatchExecuted(uint256,address,uint8,uint8)": TypedContractEvent<
      MatchExecutedEvent.InputTuple,
      MatchExecutedEvent.OutputTuple,
      MatchExecutedEvent.OutputObject
    >;
    MatchExecuted: TypedContractEvent<
      MatchExecutedEvent.InputTuple,
      MatchExecutedEvent.OutputTuple,
      MatchExecutedEvent.OutputObject
    >;
  };
}
