/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Academy__factory } from "./Academy__factory";
export { Game__factory } from "./Game__factory";
export { PlayerToken__factory } from "./PlayerToken__factory";
