/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MaliciousReentrancy,
  MaliciousReentrancyInterface,
} from "../../contracts/MaliciousReentrancy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "academyAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "gameAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "academy",
    outputs: [
      {
        internalType: "contract Academy",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "playerId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "attackAcademyBuyPlayer",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "attackAcademyExtract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "matchId",
        type: "uint256",
      },
      {
        internalType: "uint256[3][3]",
        name: "teams",
        type: "uint256[3][3]",
      },
      {
        internalType: "uint256",
        name: "wager",
        type: "uint256",
      },
    ],
    name: "attackGameAddTeam",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "callCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "game",
    outputs: [
      {
        internalType: "contract Game",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxCalls",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60803461009157601f6103b538819003918201601f19168301916001600160401b0383118484101761009657808492604094855283398101031261009157610052602061004b836100ac565b92016100ac565b6000600255600160035560018060a01b03908160018060a01b03199316836000541617600055169060015416176001556040516102f490816100c18239f35b600080fd5b634e487b7160e01b600052604160045260246000fd5b51906001600160a01b03821682036100915756fe60806040908082526004918236101561004b575b5050361561002057600080fd5b6002549060001982146100365760018201600255005b601190634e487b7160e01b6000525260246000fd5b600091823560e01c9081634b28f9a214610278575080634f5fc3c11461025157806386dbab4e146101e6578063c2fdb0311461016a578063c3fe3e2814610142578063d82d9f0d146100c25763df8d05d70361001357346100be57816003193601126100be576020906003549051908152f35b5080fd5b509181923461013e57602036600319011261013e57600283905582546001600160a01b031691823b1561013957839260248492845195869384926342d9cbc160e11b84528035908401525af1908115610130575061011d5750f35b61012690610294565b61012d5780f35b80fd5b513d84823e3d90fd5b505050fd5b5050fd5b50346100be57816003193601126100be5760015490516001600160a01b039091168152602090f35b5091819261016060031936011261013e576101443681116101395760028490556001546001600160a01b031692833b156101e257849183518095819363af6c3b4b60e01b835280359083015260606024808401376060608480840137606060e4808401378235905af1908115610130575061011d5750f35b8480fd5b5080839160031936011261024d57600283905582546001600160a01b0316918390833b156100be576044835180958193630526f8c960e21b83523081840152356024830152602435905af19081156101305750610241575080f35b61024a90610294565b80f35b8280fd5b50346100be57816003193601126100be57905490516001600160a01b039091168152602090f35b8390346100be57816003193601126100be576020906002548152f35b67ffffffffffffffff81116102a857604052565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220681b407c9f45578cef205718a5a94a52216a334539ebefbeeacb2573aabc95b764736f6c63430008150033";

type MaliciousReentrancyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousReentrancyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousReentrancy__factory extends ContractFactory {
  constructor(...args: MaliciousReentrancyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    academyAddress: AddressLike,
    gameAddress: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      academyAddress,
      gameAddress,
      overrides || {}
    );
  }
  override deploy(
    academyAddress: AddressLike,
    gameAddress: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      academyAddress,
      gameAddress,
      overrides || {}
    ) as Promise<
      MaliciousReentrancy & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MaliciousReentrancy__factory {
    return super.connect(runner) as MaliciousReentrancy__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousReentrancyInterface {
    return new Interface(_abi) as MaliciousReentrancyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousReentrancy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MaliciousReentrancy;
  }
}
