/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GameInterface extends Interface {
  getFunction(
    nameOrSignature: "getAttack" | "getDefense" | "hasDuplicates" | "playMatch"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAttack",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDefense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasDuplicates",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "playMatch",
    values: [
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getAttack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDefense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasDuplicates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "playMatch", data: BytesLike): Result;
}

export interface Game extends BaseContract {
  connect(runner?: ContractRunner | null): Game;
  waitForDeployment(): Promise<this>;

  interface: GameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAttack: TypedContractMethod<[playerId: BigNumberish], [bigint], "view">;

  getDefense: TypedContractMethod<[playerId: BigNumberish], [bigint], "view">;

  hasDuplicates: TypedContractMethod<
    [array: BigNumberish[]],
    [boolean],
    "view"
  >;

  playMatch: TypedContractMethod<
    [
      homeAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAttack"
  ): TypedContractMethod<[playerId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDefense"
  ): TypedContractMethod<[playerId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasDuplicates"
  ): TypedContractMethod<[array: BigNumberish[]], [boolean], "view">;
  getFunction(
    nameOrSignature: "playMatch"
  ): TypedContractMethod<
    [
      homeAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "payable"
  >;

  filters: {};
}
