/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Academy {
  export type AcademyPlayerStruct = {
    id: BigNumberish;
    attack: BigNumberish;
    defense: BigNumberish;
    potential: BigNumberish;
    playerType: BigNumberish;
    value: BigNumberish;
  };

  export type AcademyPlayerStructOutput = [
    id: bigint,
    attack: bigint,
    defense: bigint,
    potential: bigint,
    playerType: bigint,
    value: bigint
  ] & {
    id: bigint;
    attack: bigint;
    defense: bigint;
    potential: bigint;
    playerType: bigint;
    value: bigint;
  };
}

export interface AcademyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EXTRACT_ADDRESS"
      | "addDepositor"
      | "buyPlayer"
      | "calculateAcademyPrice"
      | "deposit"
      | "depositors"
      | "extract"
      | "getAcademyPlayers"
      | "getBalance"
      | "getPlayerValue"
      | "onERC721Received"
      | "owner"
      | "playerValue"
      | "removeDepositor"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DepositorAdded" | "DepositorRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EXTRACT_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDepositor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyPlayer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAcademyPrice",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAcademyPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDepositor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "EXTRACT_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDepositor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyPlayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateAcademyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "extract", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAcademyPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDepositor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DepositorAddedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositorRemovedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Academy extends BaseContract {
  connect(runner?: ContractRunner | null): Academy;
  waitForDeployment(): Promise<this>;

  interface: AcademyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EXTRACT_ADDRESS: TypedContractMethod<[], [string], "view">;

  addDepositor: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  buyPlayer: TypedContractMethod<
    [toAccount: AddressLike, playerId: BigNumberish],
    [void],
    "payable"
  >;

  calculateAcademyPrice: TypedContractMethod<
    [attack: BigNumberish, defense: BigNumberish, potential: BigNumberish],
    [bigint],
    "view"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  depositors: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  extract: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getAcademyPlayers: TypedContractMethod<
    [],
    [Academy.AcademyPlayerStructOutput[]],
    "view"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getPlayerValue: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  playerValue: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  removeDepositor: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EXTRACT_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addDepositor"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buyPlayer"
  ): TypedContractMethod<
    [toAccount: AddressLike, playerId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "calculateAcademyPrice"
  ): TypedContractMethod<
    [attack: BigNumberish, defense: BigNumberish, potential: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "extract"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAcademyPlayers"
  ): TypedContractMethod<[], [Academy.AcademyPlayerStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerValue"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerValue"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeDepositor"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DepositorAdded"
  ): TypedContractEvent<
    DepositorAddedEvent.InputTuple,
    DepositorAddedEvent.OutputTuple,
    DepositorAddedEvent.OutputObject
  >;
  getEvent(
    key: "DepositorRemoved"
  ): TypedContractEvent<
    DepositorRemovedEvent.InputTuple,
    DepositorRemovedEvent.OutputTuple,
    DepositorRemovedEvent.OutputObject
  >;

  filters: {
    "DepositorAdded(address)": TypedContractEvent<
      DepositorAddedEvent.InputTuple,
      DepositorAddedEvent.OutputTuple,
      DepositorAddedEvent.OutputObject
    >;
    DepositorAdded: TypedContractEvent<
      DepositorAddedEvent.InputTuple,
      DepositorAddedEvent.OutputTuple,
      DepositorAddedEvent.OutputObject
    >;

    "DepositorRemoved(address)": TypedContractEvent<
      DepositorRemovedEvent.InputTuple,
      DepositorRemovedEvent.OutputTuple,
      DepositorRemovedEvent.OutputObject
    >;
    DepositorRemoved: TypedContractEvent<
      DepositorRemovedEvent.InputTuple,
      DepositorRemovedEvent.OutputTuple,
      DepositorRemovedEvent.OutputObject
    >;
  };
}
