/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Academy {
  export type AcademyPlayerStruct = {
    id: BigNumberish;
    attack: BigNumberish;
    defense: BigNumberish;
    potential: BigNumberish;
    playerType: BigNumberish;
    value: BigNumberish;
  };

  export type AcademyPlayerStructOutput = [
    id: bigint,
    attack: bigint,
    defense: bigint,
    potential: bigint,
    playerType: bigint,
    value: bigint
  ] & {
    id: bigint;
    attack: bigint;
    defense: bigint;
    potential: bigint;
    playerType: bigint;
    value: bigint;
  };
}

export interface AcademyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EXTRACT_ADDRESS"
      | "buyPlayer"
      | "deposit"
      | "extract"
      | "getAcademyPlayers"
      | "getBalance"
      | "getPlayerValue"
      | "onERC721Received"
      | "playerValue"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "EXTRACT_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyPlayer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "extract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAcademyPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerValue",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "EXTRACT_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyPlayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "extract", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAcademyPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerValue",
    data: BytesLike
  ): Result;
}

export interface Academy extends BaseContract {
  connect(runner?: ContractRunner | null): Academy;
  waitForDeployment(): Promise<this>;

  interface: AcademyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EXTRACT_ADDRESS: TypedContractMethod<[], [string], "view">;

  buyPlayer: TypedContractMethod<
    [toAccount: AddressLike, playerId: BigNumberish],
    [void],
    "payable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  extract: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getAcademyPlayers: TypedContractMethod<
    [],
    [Academy.AcademyPlayerStructOutput[]],
    "view"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getPlayerValue: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;

  playerValue: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EXTRACT_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "buyPlayer"
  ): TypedContractMethod<
    [toAccount: AddressLike, playerId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "extract"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAcademyPlayers"
  ): TypedContractMethod<[], [Academy.AcademyPlayerStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerValue"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerValue"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  filters: {};
}
