/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Game {
  export type TeamStruct = {
    attackingPlayers: [BigNumberish, BigNumberish, BigNumberish];
    midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish];
    defensivePlayers: [BigNumberish, BigNumberish, BigNumberish];
  };

  export type TeamStructOutput = [
    attackingPlayers: [bigint, bigint, bigint],
    midfieldPlayers: [bigint, bigint, bigint],
    defensivePlayers: [bigint, bigint, bigint]
  ] & {
    attackingPlayers: [bigint, bigint, bigint];
    midfieldPlayers: [bigint, bigint, bigint];
    defensivePlayers: [bigint, bigint, bigint];
  };

  export type MatchStruct = {
    wagerRequired: BigNumberish;
    homeAddress: AddressLike;
    homeTeam: Game.TeamStruct;
    awayAddress: AddressLike;
    awayTeam: Game.TeamStruct;
    pot: BigNumberish;
  };

  export type MatchStructOutput = [
    wagerRequired: bigint,
    homeAddress: string,
    homeTeam: Game.TeamStructOutput,
    awayAddress: string,
    awayTeam: Game.TeamStructOutput,
    pot: bigint
  ] & {
    wagerRequired: bigint;
    homeAddress: string;
    homeTeam: Game.TeamStructOutput;
    awayAddress: string;
    awayTeam: Game.TeamStructOutput;
    pot: bigint;
  };
}

export interface GameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTeam"
      | "createGame"
      | "getMatch"
      | "getMatchList"
      | "matches"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchPlayed" | "NewMatch" | "PlayerScored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTeam",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addTeam", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMatchList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
}

export namespace MatchPlayedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    homeScore: BigNumberish,
    awayScore: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    homeScore: bigint,
    awayScore: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    homeScore: bigint;
    awayScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewMatchEvent {
  export type InputTuple = [matchId: BigNumberish];
  export type OutputTuple = [matchId: bigint];
  export interface OutputObject {
    matchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerScoredEvent {
  export type InputTuple = [matchId: BigNumberish, playerId: BigNumberish];
  export type OutputTuple = [matchId: bigint, playerId: bigint];
  export interface OutputObject {
    matchId: bigint;
    playerId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Game extends BaseContract {
  connect(runner?: ContractRunner | null): Game;
  waitForDeployment(): Promise<this>;

  interface: GameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTeam: TypedContractMethod<
    [
      matchId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;

  createGame: TypedContractMethod<
    [
      wagerRequired: BigNumberish,
      homeAddress: AddressLike,
      awayAddress: AddressLike
    ],
    [void],
    "payable"
  >;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [Game.MatchStructOutput],
    "view"
  >;

  getMatchList: TypedContractMethod<[], [bigint[]], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        Game.TeamStructOutput,
        string,
        Game.TeamStructOutput,
        bigint
      ] & {
        wagerRequired: bigint;
        homeAddress: string;
        homeTeam: Game.TeamStructOutput;
        awayAddress: string;
        awayTeam: Game.TeamStructOutput;
        pot: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTeam"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [
      wagerRequired: BigNumberish,
      homeAddress: AddressLike,
      awayAddress: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [Game.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatchList"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        Game.TeamStructOutput,
        string,
        Game.TeamStructOutput,
        bigint
      ] & {
        wagerRequired: bigint;
        homeAddress: string;
        homeTeam: Game.TeamStructOutput;
        awayAddress: string;
        awayTeam: Game.TeamStructOutput;
        pot: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MatchPlayed"
  ): TypedContractEvent<
    MatchPlayedEvent.InputTuple,
    MatchPlayedEvent.OutputTuple,
    MatchPlayedEvent.OutputObject
  >;
  getEvent(
    key: "NewMatch"
  ): TypedContractEvent<
    NewMatchEvent.InputTuple,
    NewMatchEvent.OutputTuple,
    NewMatchEvent.OutputObject
  >;
  getEvent(
    key: "PlayerScored"
  ): TypedContractEvent<
    PlayerScoredEvent.InputTuple,
    PlayerScoredEvent.OutputTuple,
    PlayerScoredEvent.OutputObject
  >;

  filters: {
    "MatchPlayed(uint256,uint8,uint8)": TypedContractEvent<
      MatchPlayedEvent.InputTuple,
      MatchPlayedEvent.OutputTuple,
      MatchPlayedEvent.OutputObject
    >;
    MatchPlayed: TypedContractEvent<
      MatchPlayedEvent.InputTuple,
      MatchPlayedEvent.OutputTuple,
      MatchPlayedEvent.OutputObject
    >;

    "NewMatch(uint256)": TypedContractEvent<
      NewMatchEvent.InputTuple,
      NewMatchEvent.OutputTuple,
      NewMatchEvent.OutputObject
    >;
    NewMatch: TypedContractEvent<
      NewMatchEvent.InputTuple,
      NewMatchEvent.OutputTuple,
      NewMatchEvent.OutputObject
    >;

    "PlayerScored(uint256,uint256)": TypedContractEvent<
      PlayerScoredEvent.InputTuple,
      PlayerScoredEvent.OutputTuple,
      PlayerScoredEvent.OutputObject
    >;
    PlayerScored: TypedContractEvent<
      PlayerScoredEvent.InputTuple,
      PlayerScoredEvent.OutputTuple,
      PlayerScoredEvent.OutputObject
    >;
  };
}
