/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Game {
  export type TeamStruct = {
    attackingPlayers: [BigNumberish, BigNumberish, BigNumberish];
    midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish];
    defensivePlayers: [BigNumberish, BigNumberish, BigNumberish];
  };

  export type TeamStructOutput = [
    attackingPlayers: [bigint, bigint, bigint],
    midfieldPlayers: [bigint, bigint, bigint],
    defensivePlayers: [bigint, bigint, bigint]
  ] & {
    attackingPlayers: [bigint, bigint, bigint];
    midfieldPlayers: [bigint, bigint, bigint];
    defensivePlayers: [bigint, bigint, bigint];
  };

  export type MatchStruct = {
    wagerRequired: BigNumberish;
    homeAddress: AddressLike;
    homeTeam: Game.TeamStruct;
    awayAddress: AddressLike;
    awayTeam: Game.TeamStruct;
    pot: BigNumberish;
  };

  export type MatchStructOutput = [
    wagerRequired: bigint,
    homeAddress: string,
    homeTeam: Game.TeamStructOutput,
    awayAddress: string,
    awayTeam: Game.TeamStructOutput,
    pot: bigint
  ] & {
    wagerRequired: bigint;
    homeAddress: string;
    homeTeam: Game.TeamStructOutput;
    awayAddress: string;
    awayTeam: Game.TeamStructOutput;
    pot: bigint;
  };
}

export interface GameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_WAGER"
      | "addTeam"
      | "createGame"
      | "getMatch"
      | "getMatchList"
      | "getPlayerAttributes"
      | "matches"
      | "owner"
      | "pendingWithdrawals"
      | "playMatch"
      | "playTournamentMatch"
      | "setTournamentContract"
      | "tournamentContract"
      | "validateTeam"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExtraTimePlayed"
      | "GoldenGoalPlayed"
      | "MatchPlayed"
      | "MatchSnapshot"
      | "NewMatch"
      | "PlayerMatchInfo"
      | "PlayerScored"
      | "TeamStatsCalculated"
      | "TournamentContractUpdated"
      | "TournamentMatchPlayed"
      | "WinningsDistributed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_WAGER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addTeam",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerAttributes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playMatch",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playTournamentMatch",
    values: [
      AddressLike,
      Game.TeamStruct,
      AddressLike,
      Game.TeamStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTournamentContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tournamentContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateTeam",
    values: [
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      AddressLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "MIN_WAGER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addTeam", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMatchList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "playMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playTournamentMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTournamentContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournamentContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTeam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ExtraTimePlayedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    tournamentId: BigNumberish,
    homeScore: BigNumberish,
    awayScore: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    tournamentId: bigint,
    homeScore: bigint,
    awayScore: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    tournamentId: bigint;
    homeScore: bigint;
    awayScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GoldenGoalPlayedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    tournamentId: BigNumberish,
    homeScore: BigNumberish,
    awayScore: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    tournamentId: bigint,
    homeScore: bigint,
    awayScore: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    tournamentId: bigint;
    homeScore: bigint;
    awayScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchPlayedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    homeScore: BigNumberish,
    awayScore: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    homeScore: bigint,
    awayScore: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    homeScore: bigint;
    awayScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchSnapshotEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    tournamentId: BigNumberish,
    homeAddress: AddressLike,
    awayAddress: AddressLike,
    homeTeam: Game.TeamStruct,
    awayTeam: Game.TeamStruct
  ];
  export type OutputTuple = [
    matchId: bigint,
    tournamentId: bigint,
    homeAddress: string,
    awayAddress: string,
    homeTeam: Game.TeamStructOutput,
    awayTeam: Game.TeamStructOutput
  ];
  export interface OutputObject {
    matchId: bigint;
    tournamentId: bigint;
    homeAddress: string;
    awayAddress: string;
    homeTeam: Game.TeamStructOutput;
    awayTeam: Game.TeamStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewMatchEvent {
  export type InputTuple = [matchId: BigNumberish];
  export type OutputTuple = [matchId: bigint];
  export interface OutputObject {
    matchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerMatchInfoEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    tournamentId: BigNumberish,
    playerId: BigNumberish,
    owner: AddressLike,
    attack: BigNumberish,
    defense: BigNumberish,
    potential: BigNumberish,
    gamesLeft: BigNumberish,
    goals: BigNumberish,
    playerType: BigNumberish,
    position: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    tournamentId: bigint,
    playerId: bigint,
    owner: string,
    attack: bigint,
    defense: bigint,
    potential: bigint,
    gamesLeft: bigint,
    goals: bigint,
    playerType: bigint,
    position: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    tournamentId: bigint;
    playerId: bigint;
    owner: string;
    attack: bigint;
    defense: bigint;
    potential: bigint;
    gamesLeft: bigint;
    goals: bigint;
    playerType: bigint;
    position: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerScoredEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    tournamentId: BigNumberish,
    playerId: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    tournamentId: bigint,
    playerId: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    tournamentId: bigint;
    playerId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeamStatsCalculatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    tournamentId: BigNumberish,
    team: AddressLike,
    totalAttack: BigNumberish,
    totalDefense: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    tournamentId: bigint,
    team: string,
    totalAttack: bigint,
    totalDefense: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    tournamentId: bigint;
    team: string;
    totalAttack: bigint;
    totalDefense: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentContractUpdatedEvent {
  export type InputTuple = [tournamentContract: AddressLike];
  export type OutputTuple = [tournamentContract: string];
  export interface OutputObject {
    tournamentContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournamentMatchPlayedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    tournamentMatchId: BigNumberish,
    round: BigNumberish,
    homeAddress: AddressLike,
    awayAddress: AddressLike,
    winner: AddressLike,
    homeScore: BigNumberish,
    awayScore: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    tournamentMatchId: bigint,
    round: bigint,
    homeAddress: string,
    awayAddress: string,
    winner: string,
    homeScore: bigint,
    awayScore: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    tournamentMatchId: bigint;
    round: bigint;
    homeAddress: string;
    awayAddress: string;
    winner: string;
    homeScore: bigint;
    awayScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsDistributedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winner: AddressLike,
    winnings: BigNumberish,
    academy: AddressLike,
    academyShare: BigNumberish,
    executor: AddressLike,
    executorFee: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    winner: string,
    winnings: bigint,
    academy: string,
    academyShare: bigint,
    executor: string,
    executorFee: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
    winnings: bigint;
    academy: string;
    academyShare: bigint;
    executor: string;
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Game extends BaseContract {
  connect(runner?: ContractRunner | null): Game;
  waitForDeployment(): Promise<this>;

  interface: GameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_WAGER: TypedContractMethod<[], [bigint], "view">;

  addTeam: TypedContractMethod<
    [
      matchId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;

  createGame: TypedContractMethod<
    [
      wagerRequired: BigNumberish,
      homeAddress: AddressLike,
      awayAddress: AddressLike
    ],
    [void],
    "payable"
  >;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [Game.MatchStructOutput],
    "view"
  >;

  getMatchList: TypedContractMethod<[], [bigint[]], "view">;

  getPlayerAttributes: TypedContractMethod<
    [playerId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        attack: bigint;
        level: bigint;
        defense: bigint;
        potential: bigint;
        gamesLeft: bigint;
        goals: bigint;
        playerType: bigint;
      }
    ],
    "view"
  >;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        Game.TeamStructOutput,
        string,
        Game.TeamStructOutput,
        bigint
      ] & {
        wagerRequired: bigint;
        homeAddress: string;
        homeTeam: Game.TeamStructOutput;
        awayAddress: string;
        awayTeam: Game.TeamStructOutput;
        pot: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingWithdrawals: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  playMatch: TypedContractMethod<
    [matchId: BigNumberish, executor: AddressLike],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "nonpayable"
  >;

  playTournamentMatch: TypedContractMethod<
    [
      homeAddress: AddressLike,
      homeTeam: Game.TeamStruct,
      awayAddress: AddressLike,
      awayTeam: Game.TeamStruct,
      tournamentId: BigNumberish,
      tournamentMatchId: BigNumberish,
      round: BigNumberish
    ],
    [
      [string, bigint, bigint] & {
        winner: string;
        homeGoals: bigint;
        awayGoals: bigint;
      }
    ],
    "nonpayable"
  >;

  setTournamentContract: TypedContractMethod<
    [tournamentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  tournamentContract: TypedContractMethod<[], [string], "view">;

  validateTeam: TypedContractMethod<
    [
      attack: [BigNumberish, BigNumberish, BigNumberish],
      midfield: [BigNumberish, BigNumberish, BigNumberish],
      defense: [BigNumberish, BigNumberish, BigNumberish],
      expectedOwner: AddressLike
    ],
    [boolean],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_WAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addTeam"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [
      wagerRequired: BigNumberish,
      homeAddress: AddressLike,
      awayAddress: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [Game.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatchList"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerAttributes"
  ): TypedContractMethod<
    [playerId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        attack: bigint;
        level: bigint;
        defense: bigint;
        potential: bigint;
        gamesLeft: bigint;
        goals: bigint;
        playerType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        Game.TeamStructOutput,
        string,
        Game.TeamStructOutput,
        bigint
      ] & {
        wagerRequired: bigint;
        homeAddress: string;
        homeTeam: Game.TeamStructOutput;
        awayAddress: string;
        awayTeam: Game.TeamStructOutput;
        pot: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "playMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish, executor: AddressLike],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "playTournamentMatch"
  ): TypedContractMethod<
    [
      homeAddress: AddressLike,
      homeTeam: Game.TeamStruct,
      awayAddress: AddressLike,
      awayTeam: Game.TeamStruct,
      tournamentId: BigNumberish,
      tournamentMatchId: BigNumberish,
      round: BigNumberish
    ],
    [
      [string, bigint, bigint] & {
        winner: string;
        homeGoals: bigint;
        awayGoals: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTournamentContract"
  ): TypedContractMethod<
    [tournamentAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tournamentContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validateTeam"
  ): TypedContractMethod<
    [
      attack: [BigNumberish, BigNumberish, BigNumberish],
      midfield: [BigNumberish, BigNumberish, BigNumberish],
      defense: [BigNumberish, BigNumberish, BigNumberish],
      expectedOwner: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ExtraTimePlayed"
  ): TypedContractEvent<
    ExtraTimePlayedEvent.InputTuple,
    ExtraTimePlayedEvent.OutputTuple,
    ExtraTimePlayedEvent.OutputObject
  >;
  getEvent(
    key: "GoldenGoalPlayed"
  ): TypedContractEvent<
    GoldenGoalPlayedEvent.InputTuple,
    GoldenGoalPlayedEvent.OutputTuple,
    GoldenGoalPlayedEvent.OutputObject
  >;
  getEvent(
    key: "MatchPlayed"
  ): TypedContractEvent<
    MatchPlayedEvent.InputTuple,
    MatchPlayedEvent.OutputTuple,
    MatchPlayedEvent.OutputObject
  >;
  getEvent(
    key: "MatchSnapshot"
  ): TypedContractEvent<
    MatchSnapshotEvent.InputTuple,
    MatchSnapshotEvent.OutputTuple,
    MatchSnapshotEvent.OutputObject
  >;
  getEvent(
    key: "NewMatch"
  ): TypedContractEvent<
    NewMatchEvent.InputTuple,
    NewMatchEvent.OutputTuple,
    NewMatchEvent.OutputObject
  >;
  getEvent(
    key: "PlayerMatchInfo"
  ): TypedContractEvent<
    PlayerMatchInfoEvent.InputTuple,
    PlayerMatchInfoEvent.OutputTuple,
    PlayerMatchInfoEvent.OutputObject
  >;
  getEvent(
    key: "PlayerScored"
  ): TypedContractEvent<
    PlayerScoredEvent.InputTuple,
    PlayerScoredEvent.OutputTuple,
    PlayerScoredEvent.OutputObject
  >;
  getEvent(
    key: "TeamStatsCalculated"
  ): TypedContractEvent<
    TeamStatsCalculatedEvent.InputTuple,
    TeamStatsCalculatedEvent.OutputTuple,
    TeamStatsCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentContractUpdated"
  ): TypedContractEvent<
    TournamentContractUpdatedEvent.InputTuple,
    TournamentContractUpdatedEvent.OutputTuple,
    TournamentContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TournamentMatchPlayed"
  ): TypedContractEvent<
    TournamentMatchPlayedEvent.InputTuple,
    TournamentMatchPlayedEvent.OutputTuple,
    TournamentMatchPlayedEvent.OutputObject
  >;
  getEvent(
    key: "WinningsDistributed"
  ): TypedContractEvent<
    WinningsDistributedEvent.InputTuple,
    WinningsDistributedEvent.OutputTuple,
    WinningsDistributedEvent.OutputObject
  >;

  filters: {
    "ExtraTimePlayed(uint256,uint256,uint8,uint8)": TypedContractEvent<
      ExtraTimePlayedEvent.InputTuple,
      ExtraTimePlayedEvent.OutputTuple,
      ExtraTimePlayedEvent.OutputObject
    >;
    ExtraTimePlayed: TypedContractEvent<
      ExtraTimePlayedEvent.InputTuple,
      ExtraTimePlayedEvent.OutputTuple,
      ExtraTimePlayedEvent.OutputObject
    >;

    "GoldenGoalPlayed(uint256,uint256,uint8,uint8)": TypedContractEvent<
      GoldenGoalPlayedEvent.InputTuple,
      GoldenGoalPlayedEvent.OutputTuple,
      GoldenGoalPlayedEvent.OutputObject
    >;
    GoldenGoalPlayed: TypedContractEvent<
      GoldenGoalPlayedEvent.InputTuple,
      GoldenGoalPlayedEvent.OutputTuple,
      GoldenGoalPlayedEvent.OutputObject
    >;

    "MatchPlayed(uint256,uint8,uint8)": TypedContractEvent<
      MatchPlayedEvent.InputTuple,
      MatchPlayedEvent.OutputTuple,
      MatchPlayedEvent.OutputObject
    >;
    MatchPlayed: TypedContractEvent<
      MatchPlayedEvent.InputTuple,
      MatchPlayedEvent.OutputTuple,
      MatchPlayedEvent.OutputObject
    >;

    "MatchSnapshot(uint256,uint256,address,address,tuple,tuple)": TypedContractEvent<
      MatchSnapshotEvent.InputTuple,
      MatchSnapshotEvent.OutputTuple,
      MatchSnapshotEvent.OutputObject
    >;
    MatchSnapshot: TypedContractEvent<
      MatchSnapshotEvent.InputTuple,
      MatchSnapshotEvent.OutputTuple,
      MatchSnapshotEvent.OutputObject
    >;

    "NewMatch(uint256)": TypedContractEvent<
      NewMatchEvent.InputTuple,
      NewMatchEvent.OutputTuple,
      NewMatchEvent.OutputObject
    >;
    NewMatch: TypedContractEvent<
      NewMatchEvent.InputTuple,
      NewMatchEvent.OutputTuple,
      NewMatchEvent.OutputObject
    >;

    "PlayerMatchInfo(uint256,uint256,uint256,address,uint256,uint256,uint256,uint256,uint256,uint8,uint8)": TypedContractEvent<
      PlayerMatchInfoEvent.InputTuple,
      PlayerMatchInfoEvent.OutputTuple,
      PlayerMatchInfoEvent.OutputObject
    >;
    PlayerMatchInfo: TypedContractEvent<
      PlayerMatchInfoEvent.InputTuple,
      PlayerMatchInfoEvent.OutputTuple,
      PlayerMatchInfoEvent.OutputObject
    >;

    "PlayerScored(uint256,uint256,uint256)": TypedContractEvent<
      PlayerScoredEvent.InputTuple,
      PlayerScoredEvent.OutputTuple,
      PlayerScoredEvent.OutputObject
    >;
    PlayerScored: TypedContractEvent<
      PlayerScoredEvent.InputTuple,
      PlayerScoredEvent.OutputTuple,
      PlayerScoredEvent.OutputObject
    >;

    "TeamStatsCalculated(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      TeamStatsCalculatedEvent.InputTuple,
      TeamStatsCalculatedEvent.OutputTuple,
      TeamStatsCalculatedEvent.OutputObject
    >;
    TeamStatsCalculated: TypedContractEvent<
      TeamStatsCalculatedEvent.InputTuple,
      TeamStatsCalculatedEvent.OutputTuple,
      TeamStatsCalculatedEvent.OutputObject
    >;

    "TournamentContractUpdated(address)": TypedContractEvent<
      TournamentContractUpdatedEvent.InputTuple,
      TournamentContractUpdatedEvent.OutputTuple,
      TournamentContractUpdatedEvent.OutputObject
    >;
    TournamentContractUpdated: TypedContractEvent<
      TournamentContractUpdatedEvent.InputTuple,
      TournamentContractUpdatedEvent.OutputTuple,
      TournamentContractUpdatedEvent.OutputObject
    >;

    "TournamentMatchPlayed(uint256,uint256,uint8,address,address,address,uint8,uint8)": TypedContractEvent<
      TournamentMatchPlayedEvent.InputTuple,
      TournamentMatchPlayedEvent.OutputTuple,
      TournamentMatchPlayedEvent.OutputObject
    >;
    TournamentMatchPlayed: TypedContractEvent<
      TournamentMatchPlayedEvent.InputTuple,
      TournamentMatchPlayedEvent.OutputTuple,
      TournamentMatchPlayedEvent.OutputObject
    >;

    "WinningsDistributed(uint256,address,uint256,address,uint256,address,uint256)": TypedContractEvent<
      WinningsDistributedEvent.InputTuple,
      WinningsDistributedEvent.OutputTuple,
      WinningsDistributedEvent.OutputObject
    >;
    WinningsDistributed: TypedContractEvent<
      WinningsDistributedEvent.InputTuple,
      WinningsDistributedEvent.OutputTuple,
      WinningsDistributedEvent.OutputObject
    >;
  };
}
