/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GameInterface extends Interface {
  getFunction(nameOrSignature: "playMatch"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchPlayed" | "PlayerScored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "playMatch",
    values: [
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "playMatch", data: BytesLike): Result;
}

export namespace MatchPlayedEvent {
  export type InputTuple = [homeScore: BigNumberish, awayScore: BigNumberish];
  export type OutputTuple = [homeScore: bigint, awayScore: bigint];
  export interface OutputObject {
    homeScore: bigint;
    awayScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerScoredEvent {
  export type InputTuple = [playerId: BigNumberish];
  export type OutputTuple = [playerId: bigint];
  export interface OutputObject {
    playerId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Game extends BaseContract {
  connect(runner?: ContractRunner | null): Game;
  waitForDeployment(): Promise<this>;

  interface: GameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  playMatch: TypedContractMethod<
    [
      homeAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "playMatch"
  ): TypedContractMethod<
    [
      homeAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      homeDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayAttackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayMidfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      awayDefensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [[bigint, bigint] & { homeGoals: bigint; awayGoals: bigint }],
    "payable"
  >;

  getEvent(
    key: "MatchPlayed"
  ): TypedContractEvent<
    MatchPlayedEvent.InputTuple,
    MatchPlayedEvent.OutputTuple,
    MatchPlayedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerScored"
  ): TypedContractEvent<
    PlayerScoredEvent.InputTuple,
    PlayerScoredEvent.OutputTuple,
    PlayerScoredEvent.OutputObject
  >;

  filters: {
    "MatchPlayed(uint8,uint8)": TypedContractEvent<
      MatchPlayedEvent.InputTuple,
      MatchPlayedEvent.OutputTuple,
      MatchPlayedEvent.OutputObject
    >;
    MatchPlayed: TypedContractEvent<
      MatchPlayedEvent.InputTuple,
      MatchPlayedEvent.OutputTuple,
      MatchPlayedEvent.OutputObject
    >;

    "PlayerScored(uint256)": TypedContractEvent<
      PlayerScoredEvent.InputTuple,
      PlayerScoredEvent.OutputTuple,
      PlayerScoredEvent.OutputObject
    >;
    PlayerScored: TypedContractEvent<
      PlayerScoredEvent.InputTuple,
      PlayerScoredEvent.OutputTuple,
      PlayerScoredEvent.OutputObject
    >;
  };
}
