/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Academy } from "./Academy";
export type { Game } from "./Game";
export type { PlayerToken } from "./PlayerToken";
