/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketSol from "./Market.sol";
export type { marketSol };
export type { Academy } from "./Academy";
export type { Game } from "./Game";
export type { PlayerToken } from "./PlayerToken";
