/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketSol from "./Market.sol";
export type { marketSol };
export type { Academy } from "./Academy";
export type { Game } from "./Game";
export type { MaliciousReentrancy } from "./MaliciousReentrancy";
export type { PlayerToken } from "./PlayerToken";
export type { PlayerTokenV2 } from "./PlayerTokenV2";
export type { Tournement } from "./Tournement";
