/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MaliciousReentrancyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "academy"
      | "attackAcademyBuyPlayer"
      | "attackAcademyExtract"
      | "attackGameAddTeam"
      | "callCount"
      | "game"
      | "maxCalls"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "academy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "attackAcademyBuyPlayer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attackAcademyExtract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attackGameAddTeam",
    values: [
      BigNumberish,
      [
        [BigNumberish, BigNumberish, BigNumberish],
        [BigNumberish, BigNumberish, BigNumberish],
        [BigNumberish, BigNumberish, BigNumberish]
      ],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "callCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "game", values?: undefined): string;
  encodeFunctionData(functionFragment: "maxCalls", values?: undefined): string;

  decodeFunctionResult(functionFragment: "academy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attackAcademyBuyPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attackAcademyExtract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attackGameAddTeam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "callCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "game", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxCalls", data: BytesLike): Result;
}

export interface MaliciousReentrancy extends BaseContract {
  connect(runner?: ContractRunner | null): MaliciousReentrancy;
  waitForDeployment(): Promise<this>;

  interface: MaliciousReentrancyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  academy: TypedContractMethod<[], [string], "view">;

  attackAcademyBuyPlayer: TypedContractMethod<
    [playerId: BigNumberish, price: BigNumberish],
    [void],
    "payable"
  >;

  attackAcademyExtract: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  attackGameAddTeam: TypedContractMethod<
    [
      matchId: BigNumberish,
      teams: [
        [BigNumberish, BigNumberish, BigNumberish],
        [BigNumberish, BigNumberish, BigNumberish],
        [BigNumberish, BigNumberish, BigNumberish]
      ],
      wager: BigNumberish
    ],
    [void],
    "payable"
  >;

  callCount: TypedContractMethod<[], [bigint], "view">;

  game: TypedContractMethod<[], [string], "view">;

  maxCalls: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "academy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "attackAcademyBuyPlayer"
  ): TypedContractMethod<
    [playerId: BigNumberish, price: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "attackAcademyExtract"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attackGameAddTeam"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      teams: [
        [BigNumberish, BigNumberish, BigNumberish],
        [BigNumberish, BigNumberish, BigNumberish],
        [BigNumberish, BigNumberish, BigNumberish]
      ],
      wager: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "callCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "game"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxCalls"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
