/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Game {
  export type TeamStruct = {
    attackingPlayers: [BigNumberish, BigNumberish, BigNumberish];
    midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish];
    defensivePlayers: [BigNumberish, BigNumberish, BigNumberish];
  };

  export type TeamStructOutput = [
    attackingPlayers: [bigint, bigint, bigint],
    midfieldPlayers: [bigint, bigint, bigint],
    defensivePlayers: [bigint, bigint, bigint]
  ] & {
    attackingPlayers: [bigint, bigint, bigint];
    midfieldPlayers: [bigint, bigint, bigint];
    defensivePlayers: [bigint, bigint, bigint];
  };
}

export declare namespace Tournement {
  export type TeamPlayerDetailsStruct = {
    playerId: BigNumberish;
    attack: BigNumberish;
    defense: BigNumberish;
    playerType: BigNumberish;
  };

  export type TeamPlayerDetailsStructOutput = [
    playerId: bigint,
    attack: bigint,
    defense: bigint,
    playerType: bigint
  ] & { playerId: bigint; attack: bigint; defense: bigint; playerType: bigint };

  export type TournementSummaryStruct = {
    tournamentId: BigNumberish;
    name: string;
    rounds: BigNumberish;
    entryFee: BigNumberish;
    minAttack: BigNumberish;
    minDefence: BigNumberish;
    maxAttack: BigNumberish;
    maxDefence: BigNumberish;
    includeTypes: BigNumberish[];
    excludeTypes: BigNumberish[];
    creator: AddressLike;
    teamsEntered: BigNumberish;
    maxTeams: BigNumberish;
    isOpen: boolean;
    isReady: boolean;
    cancelled: boolean;
    currentRound: BigNumberish;
    champion: AddressLike;
  };

  export type TournementSummaryStructOutput = [
    tournamentId: bigint,
    name: string,
    rounds: bigint,
    entryFee: bigint,
    minAttack: bigint,
    minDefence: bigint,
    maxAttack: bigint,
    maxDefence: bigint,
    includeTypes: bigint[],
    excludeTypes: bigint[],
    creator: string,
    teamsEntered: bigint,
    maxTeams: bigint,
    isOpen: boolean,
    isReady: boolean,
    cancelled: boolean,
    currentRound: bigint,
    champion: string
  ] & {
    tournamentId: bigint;
    name: string;
    rounds: bigint;
    entryFee: bigint;
    minAttack: bigint;
    minDefence: bigint;
    maxAttack: bigint;
    maxDefence: bigint;
    includeTypes: bigint[];
    excludeTypes: bigint[];
    creator: string;
    teamsEntered: bigint;
    maxTeams: bigint;
    isOpen: boolean;
    isReady: boolean;
    cancelled: boolean;
    currentRound: bigint;
    champion: string;
  };
}

export interface TournementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_ENTRY_FEE"
      | "TOURNEMENT_ACADEMY_BPS"
      | "cancel"
      | "claimCancelledEntry"
      | "claimReward"
      | "create"
      | "enter"
      | "getCurrentRoundEntrants"
      | "getTournements"
      | "hasClaimedReward"
      | "hasEntered"
      | "hasRefundedEntry"
      | "start"
      | "tournementAcademyFees"
      | "tournementExecutorFees"
      | "tournementMatchCounts"
      | "tournements"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TeamEntered"
      | "TournementAcademyFunded"
      | "TournementCancelled"
      | "TournementCompleted"
      | "TournementCompletedSummary"
      | "TournementCreated"
      | "TournementEntryRefunded"
      | "TournementExecutorCompensated"
      | "TournementMatchStarted"
      | "TournementReady"
      | "TournementRewardClaimed"
      | "TournementRoundAdvanced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_ENTRY_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOURNEMENT_ACADEMY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCancelledEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "enter",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentRoundEntrants",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTournements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedReward",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEntered",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRefundedEntry",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "start", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "tournementAcademyFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tournementExecutorFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tournementMatchCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tournements",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_ENTRY_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOURNEMENT_ACADEMY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimCancelledEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentRoundEntrants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTournements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasEntered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasRefundedEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tournementAcademyFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournementExecutorFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournementMatchCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tournements",
    data: BytesLike
  ): Result;
}

export namespace TeamEnteredEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    player: AddressLike,
    teamsEntered: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    player: string,
    teamsEntered: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    player: string;
    teamsEntered: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementAcademyFundedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    academyShare: BigNumberish
  ];
  export type OutputTuple = [tournamentId: bigint, academyShare: bigint];
  export interface OutputObject {
    tournamentId: bigint;
    academyShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementCancelledEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    cancelledBy: AddressLike
  ];
  export type OutputTuple = [tournamentId: bigint, cancelledBy: string];
  export interface OutputObject {
    tournamentId: bigint;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementCompletedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    champion: AddressLike,
    championWinnings: BigNumberish,
    winningTeam: Game.TeamStruct,
    winningTeamPlayers: Tournement.TeamPlayerDetailsStruct[]
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    champion: string,
    championWinnings: bigint,
    winningTeam: Game.TeamStructOutput,
    winningTeamPlayers: Tournement.TeamPlayerDetailsStructOutput[]
  ];
  export interface OutputObject {
    tournamentId: bigint;
    champion: string;
    championWinnings: bigint;
    winningTeam: Game.TeamStructOutput;
    winningTeamPlayers: Tournement.TeamPlayerDetailsStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementCompletedSummaryEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    champion: AddressLike,
    championWinnings: BigNumberish,
    executorFees: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    champion: string,
    championWinnings: bigint,
    executorFees: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    champion: string;
    championWinnings: bigint;
    executorFees: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementCreatedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    creator: AddressLike,
    name: string,
    rounds: BigNumberish,
    entryFee: BigNumberish,
    minAttack: BigNumberish,
    minDefence: BigNumberish,
    maxAttack: BigNumberish,
    maxDefence: BigNumberish,
    includeTypes: BigNumberish[],
    excludeTypes: BigNumberish[]
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    creator: string,
    name: string,
    rounds: bigint,
    entryFee: bigint,
    minAttack: bigint,
    minDefence: bigint,
    maxAttack: bigint,
    maxDefence: bigint,
    includeTypes: bigint[],
    excludeTypes: bigint[]
  ];
  export interface OutputObject {
    tournamentId: bigint;
    creator: string;
    name: string;
    rounds: bigint;
    entryFee: bigint;
    minAttack: bigint;
    minDefence: bigint;
    maxAttack: bigint;
    maxDefence: bigint;
    includeTypes: bigint[];
    excludeTypes: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementEntryRefundedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    entrant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    entrant: string,
    amount: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    entrant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementExecutorCompensatedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    executor: AddressLike,
    executorFee: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    executor: string,
    executorFee: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    executor: string;
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementMatchStartedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    tournamentMatchId: BigNumberish,
    round: BigNumberish,
    homeAddress: AddressLike,
    awayAddress: AddressLike
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    tournamentMatchId: bigint,
    round: bigint,
    homeAddress: string,
    awayAddress: string
  ];
  export interface OutputObject {
    tournamentId: bigint;
    tournamentMatchId: bigint;
    round: bigint;
    homeAddress: string;
    awayAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementReadyEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    teamsCount: BigNumberish
  ];
  export type OutputTuple = [tournamentId: bigint, teamsCount: bigint];
  export interface OutputObject {
    tournamentId: bigint;
    teamsCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementRewardClaimedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    champion: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    champion: string,
    amount: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    champion: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementRoundAdvancedEvent {
  export type InputTuple = [
    tournamentId: BigNumberish,
    completedRound: BigNumberish,
    nextRound: BigNumberish,
    teamsRemaining: BigNumberish
  ];
  export type OutputTuple = [
    tournamentId: bigint,
    completedRound: bigint,
    nextRound: bigint,
    teamsRemaining: bigint
  ];
  export interface OutputObject {
    tournamentId: bigint;
    completedRound: bigint;
    nextRound: bigint;
    teamsRemaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tournement extends BaseContract {
  connect(runner?: ContractRunner | null): Tournement;
  waitForDeployment(): Promise<this>;

  interface: TournementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  TOURNEMENT_ACADEMY_BPS: TypedContractMethod<[], [bigint], "view">;

  cancel: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimCancelledEntry: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimReward: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  create: TypedContractMethod<
    [
      name: string,
      rounds: BigNumberish,
      entryFee: BigNumberish,
      minAttack: BigNumberish,
      minDefence: BigNumberish,
      maxAttack: BigNumberish,
      maxDefence: BigNumberish,
      includeTypes: BigNumberish[],
      excludeTypes: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  enter: TypedContractMethod<
    [
      tournamentId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;

  getCurrentRoundEntrants: TypedContractMethod<
    [tournamentId: BigNumberish],
    [string[]],
    "view"
  >;

  getTournements: TypedContractMethod<
    [],
    [Tournement.TournementSummaryStructOutput[]],
    "view"
  >;

  hasClaimedReward: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasEntered: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasRefundedEntry: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  start: TypedContractMethod<
    [tournamentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  tournementAcademyFees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  tournementExecutorFees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  tournementMatchCounts: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  tournements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        name: string;
        rounds: bigint;
        entryFee: bigint;
        creator: string;
        minAttack: bigint;
        minDefence: bigint;
        maxAttack: bigint;
        maxDefence: bigint;
        teamsEntered: bigint;
        currentRound: bigint;
        cancelled: boolean;
        champion: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOURNEMENT_ACADEMY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimCancelledEntry"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<
    [
      name: string,
      rounds: BigNumberish,
      entryFee: BigNumberish,
      minAttack: BigNumberish,
      minDefence: BigNumberish,
      maxAttack: BigNumberish,
      maxDefence: BigNumberish,
      includeTypes: BigNumberish[],
      excludeTypes: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enter"
  ): TypedContractMethod<
    [
      tournamentId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getCurrentRoundEntrants"
  ): TypedContractMethod<[tournamentId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTournements"
  ): TypedContractMethod<
    [],
    [Tournement.TournementSummaryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedReward"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEntered"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRefundedEntry"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "start"
  ): TypedContractMethod<[tournamentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tournementAcademyFees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tournementExecutorFees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tournementMatchCounts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tournements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        name: string;
        rounds: bigint;
        entryFee: bigint;
        creator: string;
        minAttack: bigint;
        minDefence: bigint;
        maxAttack: bigint;
        maxDefence: bigint;
        teamsEntered: bigint;
        currentRound: bigint;
        cancelled: boolean;
        champion: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TeamEntered"
  ): TypedContractEvent<
    TeamEnteredEvent.InputTuple,
    TeamEnteredEvent.OutputTuple,
    TeamEnteredEvent.OutputObject
  >;
  getEvent(
    key: "TournementAcademyFunded"
  ): TypedContractEvent<
    TournementAcademyFundedEvent.InputTuple,
    TournementAcademyFundedEvent.OutputTuple,
    TournementAcademyFundedEvent.OutputObject
  >;
  getEvent(
    key: "TournementCancelled"
  ): TypedContractEvent<
    TournementCancelledEvent.InputTuple,
    TournementCancelledEvent.OutputTuple,
    TournementCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TournementCompleted"
  ): TypedContractEvent<
    TournementCompletedEvent.InputTuple,
    TournementCompletedEvent.OutputTuple,
    TournementCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TournementCompletedSummary"
  ): TypedContractEvent<
    TournementCompletedSummaryEvent.InputTuple,
    TournementCompletedSummaryEvent.OutputTuple,
    TournementCompletedSummaryEvent.OutputObject
  >;
  getEvent(
    key: "TournementCreated"
  ): TypedContractEvent<
    TournementCreatedEvent.InputTuple,
    TournementCreatedEvent.OutputTuple,
    TournementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TournementEntryRefunded"
  ): TypedContractEvent<
    TournementEntryRefundedEvent.InputTuple,
    TournementEntryRefundedEvent.OutputTuple,
    TournementEntryRefundedEvent.OutputObject
  >;
  getEvent(
    key: "TournementExecutorCompensated"
  ): TypedContractEvent<
    TournementExecutorCompensatedEvent.InputTuple,
    TournementExecutorCompensatedEvent.OutputTuple,
    TournementExecutorCompensatedEvent.OutputObject
  >;
  getEvent(
    key: "TournementMatchStarted"
  ): TypedContractEvent<
    TournementMatchStartedEvent.InputTuple,
    TournementMatchStartedEvent.OutputTuple,
    TournementMatchStartedEvent.OutputObject
  >;
  getEvent(
    key: "TournementReady"
  ): TypedContractEvent<
    TournementReadyEvent.InputTuple,
    TournementReadyEvent.OutputTuple,
    TournementReadyEvent.OutputObject
  >;
  getEvent(
    key: "TournementRewardClaimed"
  ): TypedContractEvent<
    TournementRewardClaimedEvent.InputTuple,
    TournementRewardClaimedEvent.OutputTuple,
    TournementRewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TournementRoundAdvanced"
  ): TypedContractEvent<
    TournementRoundAdvancedEvent.InputTuple,
    TournementRoundAdvancedEvent.OutputTuple,
    TournementRoundAdvancedEvent.OutputObject
  >;

  filters: {
    "TeamEntered(uint256,address,uint8)": TypedContractEvent<
      TeamEnteredEvent.InputTuple,
      TeamEnteredEvent.OutputTuple,
      TeamEnteredEvent.OutputObject
    >;
    TeamEntered: TypedContractEvent<
      TeamEnteredEvent.InputTuple,
      TeamEnteredEvent.OutputTuple,
      TeamEnteredEvent.OutputObject
    >;

    "TournementAcademyFunded(uint256,uint256)": TypedContractEvent<
      TournementAcademyFundedEvent.InputTuple,
      TournementAcademyFundedEvent.OutputTuple,
      TournementAcademyFundedEvent.OutputObject
    >;
    TournementAcademyFunded: TypedContractEvent<
      TournementAcademyFundedEvent.InputTuple,
      TournementAcademyFundedEvent.OutputTuple,
      TournementAcademyFundedEvent.OutputObject
    >;

    "TournementCancelled(uint256,address)": TypedContractEvent<
      TournementCancelledEvent.InputTuple,
      TournementCancelledEvent.OutputTuple,
      TournementCancelledEvent.OutputObject
    >;
    TournementCancelled: TypedContractEvent<
      TournementCancelledEvent.InputTuple,
      TournementCancelledEvent.OutputTuple,
      TournementCancelledEvent.OutputObject
    >;

    "TournementCompleted(uint256,address,uint256,tuple,tuple[])": TypedContractEvent<
      TournementCompletedEvent.InputTuple,
      TournementCompletedEvent.OutputTuple,
      TournementCompletedEvent.OutputObject
    >;
    TournementCompleted: TypedContractEvent<
      TournementCompletedEvent.InputTuple,
      TournementCompletedEvent.OutputTuple,
      TournementCompletedEvent.OutputObject
    >;

    "TournementCompletedSummary(uint256,address,uint256,uint256)": TypedContractEvent<
      TournementCompletedSummaryEvent.InputTuple,
      TournementCompletedSummaryEvent.OutputTuple,
      TournementCompletedSummaryEvent.OutputObject
    >;
    TournementCompletedSummary: TypedContractEvent<
      TournementCompletedSummaryEvent.InputTuple,
      TournementCompletedSummaryEvent.OutputTuple,
      TournementCompletedSummaryEvent.OutputObject
    >;

    "TournementCreated(uint256,address,string,uint8,uint256,uint8,uint8,uint8,uint8,uint8[],uint8[])": TypedContractEvent<
      TournementCreatedEvent.InputTuple,
      TournementCreatedEvent.OutputTuple,
      TournementCreatedEvent.OutputObject
    >;
    TournementCreated: TypedContractEvent<
      TournementCreatedEvent.InputTuple,
      TournementCreatedEvent.OutputTuple,
      TournementCreatedEvent.OutputObject
    >;

    "TournementEntryRefunded(uint256,address,uint256)": TypedContractEvent<
      TournementEntryRefundedEvent.InputTuple,
      TournementEntryRefundedEvent.OutputTuple,
      TournementEntryRefundedEvent.OutputObject
    >;
    TournementEntryRefunded: TypedContractEvent<
      TournementEntryRefundedEvent.InputTuple,
      TournementEntryRefundedEvent.OutputTuple,
      TournementEntryRefundedEvent.OutputObject
    >;

    "TournementExecutorCompensated(uint256,address,uint256)": TypedContractEvent<
      TournementExecutorCompensatedEvent.InputTuple,
      TournementExecutorCompensatedEvent.OutputTuple,
      TournementExecutorCompensatedEvent.OutputObject
    >;
    TournementExecutorCompensated: TypedContractEvent<
      TournementExecutorCompensatedEvent.InputTuple,
      TournementExecutorCompensatedEvent.OutputTuple,
      TournementExecutorCompensatedEvent.OutputObject
    >;

    "TournementMatchStarted(uint256,uint256,uint8,address,address)": TypedContractEvent<
      TournementMatchStartedEvent.InputTuple,
      TournementMatchStartedEvent.OutputTuple,
      TournementMatchStartedEvent.OutputObject
    >;
    TournementMatchStarted: TypedContractEvent<
      TournementMatchStartedEvent.InputTuple,
      TournementMatchStartedEvent.OutputTuple,
      TournementMatchStartedEvent.OutputObject
    >;

    "TournementReady(uint256,uint8)": TypedContractEvent<
      TournementReadyEvent.InputTuple,
      TournementReadyEvent.OutputTuple,
      TournementReadyEvent.OutputObject
    >;
    TournementReady: TypedContractEvent<
      TournementReadyEvent.InputTuple,
      TournementReadyEvent.OutputTuple,
      TournementReadyEvent.OutputObject
    >;

    "TournementRewardClaimed(uint256,address,uint256)": TypedContractEvent<
      TournementRewardClaimedEvent.InputTuple,
      TournementRewardClaimedEvent.OutputTuple,
      TournementRewardClaimedEvent.OutputObject
    >;
    TournementRewardClaimed: TypedContractEvent<
      TournementRewardClaimedEvent.InputTuple,
      TournementRewardClaimedEvent.OutputTuple,
      TournementRewardClaimedEvent.OutputObject
    >;

    "TournementRoundAdvanced(uint256,uint8,uint8,uint8)": TypedContractEvent<
      TournementRoundAdvancedEvent.InputTuple,
      TournementRoundAdvancedEvent.OutputTuple,
      TournementRoundAdvancedEvent.OutputObject
    >;
    TournementRoundAdvanced: TypedContractEvent<
      TournementRoundAdvancedEvent.InputTuple,
      TournementRoundAdvancedEvent.OutputTuple,
      TournementRoundAdvancedEvent.OutputObject
    >;
  };
}
