/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Tournement {
  export type TournementSummaryStruct = {
    tournementId: BigNumberish;
    rounds: BigNumberish;
    entryFee: BigNumberish;
    minAttack: BigNumberish;
    minDefence: BigNumberish;
    maxAttack: BigNumberish;
    maxDefence: BigNumberish;
    includeTypes: BigNumberish[];
    excludeTypes: BigNumberish[];
    teamsEntered: BigNumberish;
    maxTeams: BigNumberish;
    isOpen: boolean;
    champion: AddressLike;
  };

  export type TournementSummaryStructOutput = [
    tournementId: bigint,
    rounds: bigint,
    entryFee: bigint,
    minAttack: bigint,
    minDefence: bigint,
    maxAttack: bigint,
    maxDefence: bigint,
    includeTypes: bigint[],
    excludeTypes: bigint[],
    teamsEntered: bigint,
    maxTeams: bigint,
    isOpen: boolean,
    champion: string
  ] & {
    tournementId: bigint;
    rounds: bigint;
    entryFee: bigint;
    minAttack: bigint;
    minDefence: bigint;
    maxAttack: bigint;
    maxDefence: bigint;
    includeTypes: bigint[];
    excludeTypes: bigint[];
    teamsEntered: bigint;
    maxTeams: bigint;
    isOpen: boolean;
    champion: string;
  };
}

export interface TournementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimReward"
      | "create"
      | "enter"
      | "getTournements"
      | "hasClaimedReward"
      | "hasEntered"
      | "start"
      | "tournements"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TournementCompleted"
      | "TournementCreated"
      | "TournementMatchStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "enter",
    values: [
      BigNumberish,
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish],
      [BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTournements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedReward",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasEntered",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "start", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "tournements",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTournements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasEntered", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tournements",
    data: BytesLike
  ): Result;
}

export namespace TournementCompletedEvent {
  export type InputTuple = [tournementId: BigNumberish, champion: AddressLike];
  export type OutputTuple = [tournementId: bigint, champion: string];
  export interface OutputObject {
    tournementId: bigint;
    champion: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementCreatedEvent {
  export type InputTuple = [
    tournementId: BigNumberish,
    rounds: BigNumberish,
    entryFee: BigNumberish,
    minAttack: BigNumberish,
    minDefence: BigNumberish,
    maxAttack: BigNumberish,
    maxDefence: BigNumberish,
    includeTypes: BigNumberish[],
    excludeTypes: BigNumberish[]
  ];
  export type OutputTuple = [
    tournementId: bigint,
    rounds: bigint,
    entryFee: bigint,
    minAttack: bigint,
    minDefence: bigint,
    maxAttack: bigint,
    maxDefence: bigint,
    includeTypes: bigint[],
    excludeTypes: bigint[]
  ];
  export interface OutputObject {
    tournementId: bigint;
    rounds: bigint;
    entryFee: bigint;
    minAttack: bigint;
    minDefence: bigint;
    maxAttack: bigint;
    maxDefence: bigint;
    includeTypes: bigint[];
    excludeTypes: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TournementMatchStartedEvent {
  export type InputTuple = [
    tournementId: BigNumberish,
    round: BigNumberish,
    homeAddress: AddressLike,
    awayAddress: AddressLike
  ];
  export type OutputTuple = [
    tournementId: bigint,
    round: bigint,
    homeAddress: string,
    awayAddress: string
  ];
  export interface OutputObject {
    tournementId: bigint;
    round: bigint;
    homeAddress: string;
    awayAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tournement extends BaseContract {
  connect(runner?: ContractRunner | null): Tournement;
  waitForDeployment(): Promise<this>;

  interface: TournementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimReward: TypedContractMethod<
    [tournementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  create: TypedContractMethod<
    [
      rounds: BigNumberish,
      entryFee: BigNumberish,
      minAttack: BigNumberish,
      minDefence: BigNumberish,
      maxAttack: BigNumberish,
      maxDefence: BigNumberish,
      includeTypes: BigNumberish[],
      excludeTypes: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  enter: TypedContractMethod<
    [
      tournementId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;

  getTournements: TypedContractMethod<
    [],
    [Tournement.TournementSummaryStructOutput[]],
    "view"
  >;

  hasClaimedReward: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasEntered: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  start: TypedContractMethod<
    [tournementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  tournements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        rounds: bigint;
        entryFee: bigint;
        minAttack: bigint;
        minDefence: bigint;
        maxAttack: bigint;
        maxDefence: bigint;
        teamsEntered: bigint;
        champion: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[tournementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<
    [
      rounds: BigNumberish,
      entryFee: BigNumberish,
      minAttack: BigNumberish,
      minDefence: BigNumberish,
      maxAttack: BigNumberish,
      maxDefence: BigNumberish,
      includeTypes: BigNumberish[],
      excludeTypes: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enter"
  ): TypedContractMethod<
    [
      tournementId: BigNumberish,
      attackingPlayers: [BigNumberish, BigNumberish, BigNumberish],
      midfieldPlayers: [BigNumberish, BigNumberish, BigNumberish],
      defensivePlayers: [BigNumberish, BigNumberish, BigNumberish]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getTournements"
  ): TypedContractMethod<
    [],
    [Tournement.TournementSummaryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedReward"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasEntered"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "start"
  ): TypedContractMethod<[tournementId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tournements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        rounds: bigint;
        entryFee: bigint;
        minAttack: bigint;
        minDefence: bigint;
        maxAttack: bigint;
        maxDefence: bigint;
        teamsEntered: bigint;
        champion: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TournementCompleted"
  ): TypedContractEvent<
    TournementCompletedEvent.InputTuple,
    TournementCompletedEvent.OutputTuple,
    TournementCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TournementCreated"
  ): TypedContractEvent<
    TournementCreatedEvent.InputTuple,
    TournementCreatedEvent.OutputTuple,
    TournementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TournementMatchStarted"
  ): TypedContractEvent<
    TournementMatchStartedEvent.InputTuple,
    TournementMatchStartedEvent.OutputTuple,
    TournementMatchStartedEvent.OutputObject
  >;

  filters: {
    "TournementCompleted(uint256,address)": TypedContractEvent<
      TournementCompletedEvent.InputTuple,
      TournementCompletedEvent.OutputTuple,
      TournementCompletedEvent.OutputObject
    >;
    TournementCompleted: TypedContractEvent<
      TournementCompletedEvent.InputTuple,
      TournementCompletedEvent.OutputTuple,
      TournementCompletedEvent.OutputObject
    >;

    "TournementCreated(uint256,uint8,uint256,uint8,uint8,uint8,uint8,uint8[],uint8[])": TypedContractEvent<
      TournementCreatedEvent.InputTuple,
      TournementCreatedEvent.OutputTuple,
      TournementCreatedEvent.OutputObject
    >;
    TournementCreated: TypedContractEvent<
      TournementCreatedEvent.InputTuple,
      TournementCreatedEvent.OutputTuple,
      TournementCreatedEvent.OutputObject
    >;

    "TournementMatchStarted(uint256,uint8,address,address)": TypedContractEvent<
      TournementMatchStartedEvent.InputTuple,
      TournementMatchStartedEvent.OutputTuple,
      TournementMatchStartedEvent.OutputObject
    >;
    TournementMatchStarted: TypedContractEvent<
      TournementMatchStartedEvent.InputTuple,
      TournementMatchStartedEvent.OutputTuple,
      TournementMatchStartedEvent.OutputObject
    >;
  };
}
